# Settings for the app
app:
  # HTML Title
  title: Mobility Map
  # Header name
  name: Mobility Map
  # Meta description that will show up in Google search results
  meta_description: _(Mobility Map is a crowd sourcing tool used to engage the public directly with transit authorities)
  # Meta author that will show up in Google search results
  meta_author: OpenPlans.org


  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false

  geocoding_enabled: true
  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [37.2382, 121.5863, 37.4382, 122.1863]  # top, left, bottom, right

  options:
    center:
      lat: 37.3382
      lng: -121.8863
    zoom: 14
    minZoom: 10
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/examples.map-i87786ca/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">.'
    - url: /static/data/philadelphia.geojson
      type: json
      rules:
        - condition: 'true'
          style:
            color: "#444"
            opacity: 0.6
            fillOpacity: 0.1
            weight: 1

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  bike_path:
    label: _(Bike Path)
    rules:
      - condition: '"{{location_type}}" === "bike_path" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "bike_path" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]

      - condition: '"{{location_type}}" === "bike_path" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

  side_walk:
    label: _(Side Walk)
    rules:
      - condition: '"{{location_type}}" === "side_walk" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "side_walk" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]

      - condition: '"{{location_type}}" === "side_walk" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

  trail:
    label: _(Trail)
    rules:
      - condition: '"{{location_type}}" === "trail" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "bike_path" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]

      - condition: '"{{location_type}}" === "bike_path" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]


  train:
    label: _(Train)
    rules:
      - condition: '"{{location_type}}" === "train" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "bike_path" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]

      - condition: '"{{location_type}}" === "bike_path" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

  street:
    label: _(Street)
    rules:
      - condition: '"{{location_type}}" === "street" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "street" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]

      - condition: '"{{location_type}}" === "street" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

  highway:
    label: _(Highway)
    rules:
      - condition: '"{{location_type}}" === "highway" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "highway" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]

      - condition: '"{{location_type}}" === "highway" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

  bridge:
    label: _(Bridge)
    rules:
      - condition: '"{{location_type}}" === "bridge" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "bridge" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]

      - condition: '"{{location_type}}" === "bridge" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

  parking:
    label: _(Parking)
    rules:
      - condition: '"{{location_type}}" === "parking" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "parking" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]

      - condition: '"{{location_type}}" === "parking" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

        # Display landmarks as circles (vectors) when zoomed out

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Hint)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Hints)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Give us a Hint!)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location

  items:
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your Email)
      type: text
      name: private-submitter_email
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30
    - prompt: _(Hint Name)
      type: text
      name: name
      optional: true
      attrs:
        - key: placeholder
          value: _(Hint Name)
        - key: size
          value: 30
    - prompt: _(Hint Type)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Bike Path)
          value: bike_path
        - label: _(Side Walk)
          value: side_walk
        - label: _(Trail)
          value: trail
        - label: _(Street)
          value: street
        - label: _(Highway)
          value: highway
        - label: _(Bridge)
          value: bridge
        - label: _(Parking)
          value: parking
      name: location_type
      attrs:
        - key: required
    - prompt: _(Hint Category)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Hazard)
          value: hazard
        - label: _(Improvement)
          value: improvement
        - label: _(Construction)
          value: construction
      name: hint_category
      attrs:
        - key: required
    - prompt: _(Details)
      type: text
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Details Here...)
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*

survey:
  submission_type: comments

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true

  - title: _(More...)
    pages:
      - title: _(Why Mobility Map?)
        slug: why
        url: /static/pages/why.html

      - title: _(Features)
        slug: features
        url: /static/pages/features.html

  - title: _(Links)
    pages:
      - title: _(Documentation)
        external: true
        url: https://github.com/openplans/shareabouts/tree/master/doc
      - title: _(Issues)
        external: true
        url: https://github.com/openplans/shareabouts/issues
      - title: _(GitHub)
        external: true
        url: https://github.com/openplans/shareabouts

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email
